### ISSUE TITLE
Redesign Exceptions

### ISSUE THREAD

**Issue by offa** [offa/influxdb-cxx#159]
There are some specific exception classes to the HTTP transport which aren't exported symbols. Most do represent HTTP status codes.

Things to consider:

- Are the Http status exceptions necessary or can it fit into a single type with all information in it's message?
- Are message prefix and source relevant to the caller?

#### Tasks:

- [x] Deprecate non-exported Exceptions (ETA removal: 0.8.0; #165)
- [x] Remove usages of the now deprecated types
- [x] Add a message only exception ctor
- [x] Deprecate source / message exception ctor
- [x] Include message and error code in HTTP transport exceptions
